// Generated by CoffeeScript 1.9.1
"use strict";
var create, matchMethod, matchPath, methods, pathToRegexp, urlLib;

methods = require('methods');

pathToRegexp = require('./path-to-regexp');

urlLib = require('url');

matchMethod = function(req, requiredMethod) {
  var method;
  method = req.method;
  if (requiredMethod == null) {
    return true;
  }
  if (method === requiredMethod) {
    return true;
  }
  if ('HEAD' === requiredMethod && 'GET' === method) {
    return true;
  }
  return false;
};

matchPath = function(req, re, reqParams) {
  var args, i, idx, len, m, method, name, params, url, pathName;
  url = req.url, method = req.method;
  pathName = urlLib.parse(url).pathname;
  if (m = re.exec(pathName)) {
    args = m.slice(1).map(function(val) {
      if (val != null) {
        return decodeURIComponent(val);
      }
    });
    req.originatorParam = args;
    if (null !== reqParams) {
      params = {};
      for (idx = i = 0, len = reqParams.length; i < len; idx = ++i) {
        name = reqParams[idx];
        params[name] = args[idx];
      }
      req.params = params;
    }
    return true;
  } else {
    return false;
  }
};

create = function(method) {
  if (method != null) {
    method = method.toUpperCase();
  }
  return function(path, fn, opt) {
    var re, reqParams;
    re = pathToRegexp(path, opt);
    reqParams = path.match(/\:\w+\/?/g);
    if (null !== reqParams) {
      reqParams = reqParams.map(function(val) {
        var bb, ff;
        ff = 0;
        bb = val.length;
        if (0 === val.indexOf('\/\:')) {
          ff = 2;
        } else if (0 === val.indexOf('\:')) {
          ff = 1;
        }
        if (val.length - 1 === val.lastIndexOf('\/')) {
          bb -= 1;
        }
        return val.substring(ff, bb);
      });
    }
    if ('GeneratorFunction' === fn.constructor.name) {
      return function*(req, res, next) {
        if (!matchMethod(req, method)) {
          return (yield next);
        }
        if (true === matchPath(req, re, reqParams)) {
          (yield fn(req, res, next));
          return;
        }
        return (yield next);
      };
    } else {
      return function(req, res, next) {
        if (!matchMethod(req, method)) {
          return next();
        }
        if (true === matchPath(req, re, reqParams)) {
          fn(req, res, next);
          return;
        }
        return next();
      };
    }
  };
};

methods.forEach(function(method) {
  return exports[method] = create(method);
});

exports.all = create();
